# Generated by Django 3.1 on 2021-02-07 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guser',
            name='commute_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guser',
            name='commute_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
