# Generated by Django 3.1 on 2021-02-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20210207_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='guser',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
